---
- name: install apache
  become: true
  ansible.builtin.yum:
    name: "httpd"
    state: present

- name: install git
  become: true
  ansible.builtin.yum:
    name: "git"
    state: present

- name: clone a repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/Graceful-star/tooling-1.git
    dest: /home/ec2-user/
    force: yes

- name: copy html content to one level up
  ansible.builtin.copy:
    src: /home/ec2-user/
    dest: /var/www/html
    remote_src: yes

- name: Start service httpd, if not started
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: recursively remove /var/www/html/ directory
  become: true
  ansible.builtin.file:
    path: /var/www/html
    state: absent 