[nfs]
172.31.27.194 ansible_ssh_user='ec2-user'

[webservers]
172.31.19.86 ansible_ssh_user='ec2-user'
172.31.28.233 ansible_ssh_user='ec2-user'

[db]
172.31.17.250 ansible_ssh_user='ec2-user' 

[lb]
172.31.26.163 ansible_ssh_user='ubuntu'