---
- name: import common file
  import_playbook: ../static-assignments/common.yml
  tags:
   - always

- name: include env-vars file
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
   - always

- name: import database file
  import_playbook: ../static-assignments/db.yml

- name: import uat-webservers file
  import_playbook: ../static-assignments/uat-webservers.yml

- name: import loadbalancers file
  import_playbook: ../static-assignments/lb.yml
  when: loadbalancer_is_required

  